# Site settings
title: Plottico - the simplest way to create real-time live plots
tag_text: Plotti.co <sup style='font-size:35%; top:-1.5em;color:gray'><i>beta</i></sup>
description: Plottico is a web api that generates live plots in SVG images.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
